## **24ADI006 - DEEP LEARNING** - PERCEPTRON IMPLEMENTATION

***-SREENIDHI S (24BAD114)***






### **TASK 1: Single layer Perceptron for AND and OR Logic Gates.**

**Aim:** To create a Single Layer Perceptron from scratch and implement the AND and OR binary logic gates using the perceptron learning algorithm.




**Step 1:** Import the required Library

In [ ]:
import numpy as np

**Step 2:** Create the Perceptron Class

In [ ]:
class Perceptron:
    def __init__(self, num_inputs, learning_rate=0.1):
        # Initialize weights and bias
        self.weights = np.random.rand(num_inputs + 1)
        self.learning_rate = learning_rate

    def linear(self, inputs):
        # Calculate weighted sum
        return np.dot(inputs, self.weights[1:]) + self.weights[0]

    def activation(self, z):
        # Heaviside Step Function
        if z >= 0:
            return 1
        else:
            return 0

    def predict(self, inputs):
        # Predict output
        z = self.linear(inputs)
        return self.activation(z)

    def train(self, inputs, target):
        prediction = self.predict(inputs)
        error = target - prediction

        # Update weights
        self.weights[1:] += self.learning_rate * error * inputs

        # Update bias
        self.weights[0] += self.learning_rate * error

    def fit(self, X, y, epochs=20):
        for epoch in range(epochs):
            for inputs, target in zip(X, y):
                self.train(inputs, target)

**Explanation:**
* The class initializes random weights and bias.
* The linear function computes Z = XW + b.
* The activation function converts the output into 0 or 1.
* The train function updates the weights using the perceptron learning rule.
* The fit function trains the model for multiple epochs.

**AND LOGIC GATE** - Training Data

In [ ]:
X_and = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_and = np.array([0,0,0,1])

**Train the Model**

In [ ]:
and_model = Perceptron(num_inputs=2, learning_rate=0.1)

and_model.fit(X_and, y_and, epochs=100)

**Explanation:**

* The perceptron is trained using the AND truth table for 100 epochs.

**Test the Model**

In [ ]:
print("AND Gate Predictions")

for x in X_and:
    print(f"{x} -> {and_model.predict(x)}")

AND Gate Predictions
[0 0] -> 0
[0 1] -> 0
[1 0] -> 0
[1 1] -> 1


**OR Logic Gate** - Training Data

In [ ]:
X_or = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_or = np.array([0,1,1,1])

**Train the Model**

In [ ]:
or_model = Perceptron(num_inputs=2, learning_rate=0.1)

or_model.fit(X_or, y_or, epochs=100)

**Test the Model**

In [ ]:
print("OR Gate Predictions")

for x in X_or:
    print(f"{x} -> {or_model.predict(x)}")


OR Gate Predictions
[0 0] -> 0
[0 1] -> 1
[1 0] -> 1
[1 1] -> 1


**Improving the Model Accuracy**

To improve the learning performance of the perceptron:

* Increase the number of epochs (e.g., from 20 to 100).
* Choose a suitable learning rate (e.g., 0.1).
* Train the model until it correctly classifies all the training samples.

In [ ]:
# Calculate AND Gate Accuracy
correct = 0

for x, y_true in zip(X_and, y_and):
    prediction = and_model.predict(x)
    if prediction == y_true:
        correct += 1

accuracy = (correct / len(y_and)) * 100

print(f"AND Gate Accuracy: {accuracy:.2f}%")

# Calculate OR Gate Accuracy
correct = 0

for x, y_true in zip(X_or, y_or):
    prediction = or_model.predict(x)
    if prediction == y_true:
        correct += 1

accuracy = (correct / len(y_or)) * 100

print(f"OR Gate Accuracy: {accuracy:.2f}%")

AND Gate Accuracy: 100.00%
OR Gate Accuracy: 100.00%


**Conclusion**

The Single Layer Perceptron was successfully implemented from scratch. The model correctly learned the AND and OR logic gates by updating its weights and bias during training. After sufficient training epochs, the perceptron achieved 100% accuracy on both logic gate truth tables.

### **TASK 2: Train, Predict and Calculate Accuracy Using the Iris Dataset**

**Aim**

To generate a random dataset, train a Single Layer Perceptron model, predict the output, and evaluate the model by calculating its accuracy.

**Step 1:** Import Required Libraries

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

**Step 2:** Generate a Random Dataset

In [ ]:
np.random.seed(42)

# Generate 100 samples with 4 input features
X = np.random.randint(0, 10, (100, 4))

# Generate target labels
y = np.array([1 if np.sum(sample) >= 20 else 0 for sample in X])

print("Features:")
print(X[:10])

print("\nTarget Labels:")
print(y[:10])

Features:
[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]
 [1 7 5 1]
 [4 0 9 5]
 [8 0 9 2]
 [6 3 8 2]
 [4 2 6 4]
 [8 6 1 3]]

Target Labels:
[1 1 1 0 0 0 0 0 0 0]


**Step 3:** Split the Dataset into Training and Testing Sets

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 80
Testing Samples: 20


**Step 4:** Create the Perceptron Model

In [ ]:
dataset_model = Perceptron(num_inputs=4, learning_rate=0.1)

**Step 5:** Train the Model

In [ ]:
dataset_model.fit(X_train, y_train, epochs=100)

print("Model Trained Successfully!")

Model Trained Successfully!


**Step 6:** Predict the Test Data

In [ ]:
predictions = []

print("Predictions:")

for x in X_test:
    prediction = dataset_model.predict(x)
    predictions.append(prediction)
    print(f"{x} -> {prediction}")

Predictions:
[9 6 9 2] -> 1
[6 3 8 0] -> 0
[5 5 5 2] -> 0
[6 4 0 0] -> 0
[0 1 1 5] -> 0
[0 2 9 7] -> 0
[7 2 2 0] -> 0
[5 6 1 9] -> 0
[8 1 9 8] -> 1
[6 3 7 4] -> 1
[1 4 7 9] -> 1
[9 9 2 6] -> 1
[3 2 0 0] -> 0
[2 5 1 9] -> 0
[3 9 5 5] -> 1
[1 7 5 1] -> 0
[2 0 3 4] -> 0
[6 0 2 1] -> 0
[6 7 2 0] -> 0
[0 3 3 4] -> 0


**Step 7:** Calculate the Accuracy

In [28]:
correct = 0

for prediction, actual in zip(predictions, y_test):
    if prediction == actual:
        correct += 1

accuracy = (correct / len(y_test)) * 100

print(f"Model Accuracy: {accuracy:.2f}%")

Model Accuracy: 95.00%


**Result**

The Single Layer Perceptron was successfully trained on the random dataset. The model predicted the test samples correctly and achieved an accuracy of 95%.

